var APP={
  SID:'1fZ3Q88T_5ggfXyXWCRCu8epeSn0qyf2LzvVlcJlW6rI',
  S:{A:'Accounts',Q:'Questions',T:'Attempts',R:'Responses',G:'Settings',U:'Students'},
  C:['สินทรัพย์','หนี้สิน','ส่วนของเจ้าของ'],D:['เพิ่มขึ้น','ลดลง'],F:['A','B','C','D','E'],
  DEF:{exam_title:'แบบทดสอบการวิเคราะห์รายการค้า',question_count:20,exam_time:30,pass_percent:60}
};
function doGet(e){var v=e&&e.parameter&&e.parameter.view==='teacher'?'teacher':'student';return HtmlService.createHtmlOutput(page_(v)).setTitle(APP.DEF.exam_title).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL).addMetaTag('viewport','width=device-width,initial-scale=1');}
function ss_(){return SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID')||APP.SID);}
function sh_(n){var s=ss_().getSheetByName(n);if(!s)throw new Error('ไม่พบชีต '+n);return s;}
function table_(n){var v=sh_(n).getDataRange().getValues();if(!v.length)return[];var h=v[0].map(function(x){return String(x).trim();});return v.slice(1).filter(function(r){return r.some(function(x){return x!==''&&x!=null;});}).map(function(r,i){var o={_row:i+2};h.forEach(function(k,j){if(k)o[k]=r[j];});return o;});}
function heads_(n){var s=sh_(n),c=s.getLastColumn();return c?s.getRange(1,1,1,c).getValues()[0].map(function(x){return String(x).trim();}):[];}
function append_(n,objs){if(!objs||!objs.length)return;var s=sh_(n),h=heads_(n),rows=objs.map(function(o){return h.map(function(k){return o[k]==null?'':o[k];});});s.getRange(s.getLastRow()+1,1,rows.length,h.length).setValues(rows);}
function patch_(n,row,p){var s=sh_(n),h=heads_(n),v=s.getRange(row,1,1,h.length).getValues()[0];h.forEach(function(k,i){if(Object.prototype.hasOwnProperty.call(p,k))v[i]=p[k];});s.getRange(row,1,1,h.length).setValues([v]);}
function find_(n,k,val){var a=table_(n);for(var i=0;i<a.length;i++)if(String(a[i][k]).trim()===String(val).trim())return a[i];return null;}
function settings_(){var o={};table_(APP.S.G).forEach(function(r){if(r.Setting)o[String(r.Setting).trim()]=r.Value;});Object.keys(APP.DEF).forEach(function(k){if(o[k]==null||o[k]==='')o[k]=APP.DEF[k];});o.question_count=Number(o.question_count)||20;o.exam_time=Number(o.exam_time)||30;o.pass_percent=Number(o.pass_percent)||60;return o;}
function getBootstrapData(){var s=settings_();return{config:{title:s.exam_title,questionCount:s.question_count,examTimeMinutes:s.exam_time,passPercent:s.pass_percent,categories:APP.C,changes:APP.D},accounts:table_(APP.S.A).filter(function(r){return String(r.Active).toUpperCase()!=='FALSE';}).map(function(r){return{name:r.AccountName,category:r.Category};})};}
function getStudentProfile(id){id=String(id||'').trim();if(!id)throw new Error('กรุณากรอกรหัสประจำตัวนักเรียน');var r=find_(APP.S.U,'StudentID',id);if(!r)throw new Error('ไม่พบรหัสนักเรียน '+id+' ในระบบ');if(String(r.Active).toUpperCase()==='FALSE')throw new Error('รหัสนักเรียนนี้ถูกปิดการใช้งาน');return{studentId:String(r.StudentID),firstName:String(r.FirstName||''),lastName:String(r.LastName||''),className:String(r.Class||''),room:String(r.Room||''),number:String(r.Number||'')};}
function qrow_(r){var n=Number(r.AnswerCount)||2,k=[];for(var i=1;i<=n;i++)k.push({account:r['Account'+i],category:r['Category'+i],change:r['Change'+i]});return{id:String(r.QuestionID),form:String(r.FormID),seq:Number(r.Sequence),text:String(r.QuestionText),difficulty:String(r.Difficulty||''),answerCount:n,key:k};}
function qform_(f){return table_(APP.S.Q).filter(function(r){return String(r.FormID)===String(f)&&String(r.Active).toUpperCase()!=='FALSE';}).map(qrow_).sort(function(a,b){return a.seq-b.seq;});}
function shuffle_(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t;}return a;}
function pub_(q){return{id:q.id,text:q.text,difficulty:q.difficulty,answerCount:q.answerCount};}
function aid_(){return'AT-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Bangkok','yyyyMMdd')+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase();}
function startExam(x){var st=getStudentProfile(x&&x.studentId!=null?x.studentId:x),s=settings_(),f=APP.F[Math.floor(Math.random()*APP.F.length)],qs=qform_(f);if(qs.length<s.question_count)throw new Error('ข้อสอบชุด '+f+' มีไม่ครบ '+s.question_count+' ข้อ');qs=shuffle_(qs).slice(0,s.question_count);var now=new Date(),id=aid_(),lock=LockService.getScriptLock();lock.waitLock(10000);try{append_(APP.S.T,[{AttemptID:id,StudentID:st.studentId,FirstName:st.firstName,LastName:st.lastName,Class:st.className,Room:st.room,Number:st.number,FormID:f,StartTime:now,Status:'IN_PROGRESS',QuestionIDs:JSON.stringify(qs.map(function(q){return q.id;}))}]);}finally{lock.releaseLock();}return{attemptId:id,formId:f,expiresAt:new Date(now.getTime()+s.exam_time*60000).toISOString(),questions:qs.map(pub_),student:st};}
function clean_(x){return x==null?'':String(x).trim();}
function norm_(rows){var seen={};return(rows||[]).map(function(r){return{account:clean_(r&&r.account),category:clean_(r&&r.category),change:clean_(r&&r.change)};}).filter(function(r){return r.account||r.category||r.change;}).filter(function(r){var k=r.account+'|'+r.category+'|'+r.change;if(seen[k])return false;seen[k]=1;return true;});}
function gradeQ_(key,ans){key=norm_(key);ans=norm_(ans);var by={},n=key.length||1,a=0,c=0,d=0;ans.forEach(function(r){if(r.account&&!by[r.account])by[r.account]=r;});key.forEach(function(k){var r=by[k.account];if(!r)return;a++;if(r.category===k.category)c++;if(r.change===k.change)d++;});return{score:(a/n+c/n+d/n)/3,accountScore:a/n,categoryScore:c/n,changeScore:d/n};}
function grade_(keys,res){var ids=Object.keys(keys),n=ids.length||1,t=0,a=0,c=0,d=0,qr={};ids.forEach(function(id){var r=gradeQ_(keys[id],(res||{})[id]||[]);qr[id]=r;t+=r.score;a+=r.accountScore;c+=r.categoryScore;d+=r.changeScore;});function p(x){return Math.round(x/n*10000)/100;}return{percent:p(t),accountPercent:p(a),categoryPercent:p(c),changePercent:p(d),questionResults:qr};}
function result_(a){return{studentName:(a.FirstName+' '+a.LastName).trim(),className:a.Class,room:a.Room,number:a.Number,formId:a.FormID,percent:Number(a.Percent)||0,accountPercent:Number(a.AccountScore)||0,categoryPercent:Number(a.CategoryScore)||0,changePercent:Number(a.ChangeScore)||0,status:a.Status};}
function submitExam(p){if(!p||!/^AT-\d{8}-[A-Z0-9]{8}$/.test(String(p.attemptId||'')))throw new Error('AttemptID ไม่ถูกต้อง');var lock=LockService.getScriptLock();lock.waitLock(15000);try{var a=find_(APP.S.T,'AttemptID',p.attemptId);if(!a)throw new Error('ไม่พบรหัสการสอบ');if(a.SubmitTime)return result_(a);var all=qform_(a.FormID),map={},by={};all.forEach(function(q){map[q.id]=q.key;by[q.id]=q;});var ids=[];try{ids=JSON.parse(String(a.QuestionIDs||'[]'));}catch(e){}if(!ids.length)ids=all.map(function(q){return q.id;});var keys={};ids.forEach(function(id){if(map[id])keys[id]=map[id];});var g=grade_(keys,p.responses||{}),s=settings_(),now=new Date(),status=g.percent>=s.pass_percent?'ผ่าน':'ควรทบทวน';append_(APP.S.R,ids.filter(function(id){return by[id];}).map(function(id){var r=g.questionResults[id];return{AttemptID:a.AttemptID,QuestionID:id,StudentAnswerJSON:JSON.stringify((p.responses||{})[id]||[]),Score:Math.round(r.score*10000)/100,AccountScore:Math.round(r.accountScore*10000)/100,CategoryScore:Math.round(r.categoryScore*10000)/100,ChangeScore:Math.round(r.changeScore*10000)/100};}));var dur=Math.max(0,Math.round((now-new Date(a.StartTime))/1000));patch_(APP.S.T,a._row,{SubmitTime:now,DurationSeconds:dur,RawScore:Math.round(g.percent/100*ids.length*100)/100,Percent:g.percent,AccountScore:g.accountPercent,CategoryScore:g.categoryPercent,ChangeScore:g.changePercent,Status:status});a.SubmitTime=now;a.Percent=g.percent;a.AccountScore=g.accountPercent;a.CategoryScore=g.categoryPercent;a.ChangeScore=g.changePercent;a.Status=status;return result_(a);}finally{lock.releaseLock();}}
function admin_(key){var x=PropertiesService.getScriptProperties().getProperty('ADMIN_KEY');if(!x)throw new Error('กรุณาตั้ง ADMIN_KEY ใน Script Properties');if(String(key||'')!==String(x))throw new Error('รหัสผู้ดูแลไม่ถูกต้อง');}
function getDashboardData(key){admin_(key);var a=table_(APP.S.T).filter(function(r){return!!r.SubmitTime;}),nums=a.map(function(r){return Number(r.Percent)||0;}),pass=a.filter(function(r){return String(r.Status)==='ผ่าน';}).length,avg=nums.length?nums.reduce(function(x,y){return x+y;},0)/nums.length:0;return{summary:{total:a.length,pass:pass,review:a.length-pass,average:Math.round(avg*100)/100,highest:nums.length?Math.max.apply(null,nums):0,lowest:nums.length?Math.min.apply(null,nums):0},attempts:a.map(function(r){return{studentId:r.StudentID,name:(r.FirstName+' '+r.LastName).trim(),className:r.Class,room:r.Room,number:r.Number,formId:r.FormID,percent:Number(r.Percent)||0,accountPercent:Number(r.AccountScore)||0,categoryPercent:Number(r.CategoryScore)||0,changePercent:Number(r.ChangeScore)||0,status:r.Status,submitTime:r.SubmitTime?new Date(r.SubmitTime).toISOString():''};})};}
function page_(view){var V=JSON.stringify(view);return `<!doctype html><html lang="th"><head><base target="_top"><meta charset="utf-8"><link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@400;600;700&display=swap" rel="stylesheet"><style>
*{box-sizing:border-box}body{margin:0;background:#f4f8fc;color:#17324d;font-family:Sarabun,sans-serif}.hide{display:none!important}header{background:#15385f;color:#fff;padding:16px max(16px,calc((100vw - 1100px)/2));display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:3}header b{font-size:20px}#timer{background:#ffffff20;border:1px solid #ffffff50;border-radius:10px;padding:8px 12px;font-weight:700}.wrap{width:min(1100px,calc(100% - 24px));margin:24px auto}.card{background:#fff;border:1px solid #d7e3ef;border-radius:18px;padding:24px;box-shadow:0 10px 28px #15385f12}.center{max-width:620px;margin:70px auto}.muted{color:#6b7e90}.row{display:flex;gap:10px}.row input{flex:1}.btn,input,select{font:inherit}.btn{border:0;border-radius:11px;padding:11px 16px;font-weight:700;cursor:pointer}.primary{background:#2878c7;color:#fff}.secondary{background:#edf3f8;color:#15385f}.success{background:#238b57;color:#fff}input,select{border:1px solid #cbd8e4;border-radius:10px;padding:11px;background:#fff}input:focus,select:focus{outline:3px solid #2878c722;border-color:#2878c7}.info{background:#eef6ff;padding:14px;border-radius:12px;margin:18px 0}.meta{display:flex;justify-content:space-between;gap:10px;margin-bottom:12px}.grid{display:grid;grid-template-columns:180px 1fr;gap:16px}.nav{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.nav button{border:1px solid #d8e4ef;border-radius:9px;background:#f8fafc;padding:9px;cursor:pointer}.nav button.ok{background:#e8f6ee;color:#23774d}.nav button.cur{outline:3px solid #2878c722;border-color:#2878c7}.q h2{line-height:1.55;color:#15385f}.tbl{overflow:auto}.tbl table{width:100%;min-width:620px;border-collapse:separate;border-spacing:0 9px}.tbl th{text-align:left;color:#6b7e90}.tbl td,.tbl th{padding:0 6px}.tbl select{width:100%}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.score{text-align:center;font-size:70px;font-weight:700;color:#15385f}.skills,.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.skill,.sum{border:1px solid #d8e4ef;border-radius:12px;padding:14px}.skill b,.sum b{display:block;font-size:22px;color:#15385f}.recommend{margin-top:16px;background:#eef6ff;border-left:4px solid #2878c7;padding:14px}.dash{overflow:auto}.dash table{width:100%;border-collapse:collapse;white-space:nowrap}.dash th,.dash td{padding:9px;border-bottom:1px solid #e4edf5;text-align:left;font-size:13px}.modal{position:fixed;inset:0;background:#0b223855;display:grid;place-items:center;padding:20px;z-index:10}.toast{position:fixed;left:50%;bottom:20px;transform:translateX(-50%);background:#20384d;color:#fff;padding:10px 14px;border-radius:10px;z-index:20}@media(max-width:760px){.grid{grid-template-columns:1fr}.nav{grid-template-columns:repeat(5,1fr)}.row{flex-direction:column}.skills,.summary{grid-template-columns:1fr}.wrap{margin:14px auto}.card{padding:18px}.score{font-size:54px}}
</style></head><body><header><div><b id="title">แบบทดสอบการวิเคราะห์รายการค้า</b><div style="opacity:.75;font-size:13px">สินทรัพย์ • หนี้สิน • ส่วนของเจ้าของ</div></div><div id="timer" class="hide">30:00</div></header><main class="wrap">
<section id="load" class="card center"><p>กำลังเตรียมระบบ...</p></section>
<section id="start" class="card center hide"><h1>เริ่มทำแบบทดสอบ</h1><p class="muted">กรอกรหัสประจำตัวนักเรียน ระบบจะดึงข้อมูลจากรายชื่อในชีต Students</p><div class="info">จำนวน <b id="qc">20</b> ข้อ • เวลา <b id="tm">30</b> นาที • เกณฑ์ผ่าน <b id="pp">60</b>%</div><form id="sf" class="row"><input id="sid" required inputmode="numeric" placeholder="รหัสประจำตัวนักเรียน"><button class="btn primary">เริ่มทำแบบทดสอบ</button></form></section>
<section id="exam" class="hide"><div class="meta"><div><b id="sn"></b><div class="muted" id="sm"></div></div><b>ชุด <span id="form"></span></b></div><div class="grid"><aside class="card"><b>ข้อสอบ</b><div id="nav" class="nav" style="margin-top:12px"></div></aside><section class="card q"><div class="muted" id="pos"></div><h2 id="qt"></h2><div class="tbl"><table><thead><tr><th>บัญชีที่เกี่ยวข้อง</th><th>หมวดบัญชี</th><th>เพิ่ม/ลด</th></tr></thead><tbody id="rows"></tbody></table></div><div class="actions"><button id="prev" class="btn secondary">ย้อนกลับ</button><button id="next" class="btn primary">ถัดไป</button><button id="send" class="btn success hide">ส่งคำตอบ</button></div></section></div></section>
<section id="result" class="card hide"><div id="status" style="text-align:center;font-weight:700"></div><div id="pct" class="score">0%</div><h2 id="rn" style="text-align:center"></h2><p id="rm" class="muted" style="text-align:center"></p><div class="skills"><div class="skill">ระบุบัญชี<b id="sa">0%</b></div><div class="skill">จำแนกหมวดบัญชี<b id="sc">0%</b></div><div class="skill">วิเคราะห์เพิ่ม/ลด<b id="sd">0%</b></div></div><div id="rec" class="recommend"></div><div class="actions"><button id="home" class="btn secondary">กลับหน้าแรก</button></div></section>
<section id="teacher" class="hide"><div id="login" class="card center"><h1>แดชบอร์ดครู</h1><div class="row"><input id="key" type="password" placeholder="ADMIN_KEY"><button id="go" class="btn primary">เข้าสู่ระบบ</button></div></div><div id="db" class="hide"><div class="row" style="justify-content:space-between;margin-bottom:12px"><input id="search" placeholder="ค้นหาชื่อ/รหัส/ห้อง"><button id="csv" class="btn secondary">Export CSV</button></div><div id="sum" class="summary"></div><div class="card dash" style="margin-top:12px"><table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>ชั้น/ห้อง</th><th>ชุด</th><th>รวม</th><th>บัญชี</th><th>หมวด</th><th>เพิ่ม/ลด</th><th>สถานะ</th></tr></thead><tbody id="body"></tbody></table></div></div></section>
</main><div id="modal" class="modal hide"><div class="card" style="max-width:420px"><h3>ยืนยันการส่ง</h3><p id="mm"></p><div class="actions"><button id="cancel" class="btn secondary">ยกเลิก</button><button id="confirm" class="btn primary">ยืนยัน</button></div></div></div><div id="toast" class="toast hide"></div><script>window.VIEW=`+V+`;
(function(){'use strict';var K='ataot:v3',S={cfg:null,acc:[],st:null,a:null,qs:[],ans:{},i:0,t:null,db:null};function $(x){return document.getElementById(x)}function gas(n){var a=[].slice.call(arguments,1);return new Promise(function(ok,no){var r=google.script.run.withSuccessHandler(ok).withFailureHandler(function(e){no(new Error(e&&e.message?e.message:String(e)))});if(a.length===0)r[n]();else if(a.length===1)r[n](a[0]);else r[n](a[0],a[1]);})}function only(id){['load','start','exam','result','teacher'].forEach(function(x){$(x).classList.toggle('hide',x!==id)})}function toast(m){var e=$('toast');e.textContent=m;e.classList.remove('hide');clearTimeout(toast.x);toast.x=setTimeout(function(){e.classList.add('hide')},3000)}function busy(b,on,txt){if(!b)return;if(on){b.dataset.x=b.textContent;b.disabled=true;b.textContent=txt}else{b.disabled=false;b.textContent=b.dataset.x||b.textContent}}function pc(x){return Math.round(Number(x)||0)+'%'}
async function boot(){try{if(window.VIEW==='teacher'){only('teacher');bindT();return}var d=await gas('getBootstrapData');S.cfg=d.config;S.acc=d.accounts;$('title').textContent=d.config.title;$('qc').textContent=d.config.questionCount;$('tm').textContent=d.config.examTimeMinutes;$('pp').textContent=d.config.passPercent;bind();if(!restore())only('start')}catch(e){only('start');toast(e.message)}}function bind(){$('sf').onsubmit=start;$('prev').onclick=function(){go(S.i-1)};$('next').onclick=function(){go(S.i+1)};$('send').onclick=ask;$('cancel').onclick=function(){$('modal').classList.add('hide')};$('confirm').onclick=function(){$('modal').classList.add('hide');submit()};$('home').onclick=function(){localStorage.removeItem(K);location.reload()}}
async function start(e){e.preventDefault();var b=e.submitter||$('sf').querySelector('button');busy(b,true,'กำลังสร้างข้อสอบ...');try{var a=await gas('startExam',{studentId:$('sid').value.trim()});S.a=a;S.st=a.student;S.qs=a.questions;S.ans={};S.i=0;S.qs.forEach(function(q){S.ans[q.id]=Array.from({length:q.answerCount},function(){return{account:'',category:'',change:''}})});save();showExam()}catch(x){toast(x.message)}finally{busy(b,false)}}function showExam(){only('exam');$('timer').classList.remove('hide');$('sn').textContent=S.st.firstName+' '+S.st.lastName;$('sm').textContent=S.st.className+'/'+S.st.room+' เลขที่ '+S.st.number;$('form').textContent=S.a.formId;nav();render();timer()}
function nav(){var n=$('nav');n.innerHTML='';S.qs.forEach(function(q,i){var b=document.createElement('button');b.textContent=i+1;b.onclick=function(){go(i)};n.appendChild(b)});navState()}function done(q){return(S.ans[q.id]||[]).every(function(r){return r.account&&r.category&&r.change})}function navState(){Array.prototype.slice.call($('nav').children).forEach(function(b,i){b.classList.toggle('ok',done(S.qs[i]));b.classList.toggle('cur',i===S.i)})}function opts(a,val,field,row){var s=document.createElement('select'),z=document.createElement('option');z.value='';z.textContent='— เลือก —';s.appendChild(z);a.forEach(function(x){var o=document.createElement('option');o.value=x;o.textContent=x;s.appendChild(o)});s.value=val||'';s.onchange=function(){S.ans[S.qs[S.i].id][row][field]=s.value;save();navState()};return s}function render(){var q=S.qs[S.i];$('pos').textContent='ข้อ '+(S.i+1)+' จาก '+S.qs.length+' • '+q.difficulty;$('qt').textContent=q.text;var t=$('rows');t.innerHTML='';S.ans[q.id].forEach(function(r,i){var tr=document.createElement('tr'),a=document.createElement('td'),c=document.createElement('td'),d=document.createElement('td');a.appendChild(opts(S.acc.map(function(x){return x.name}),r.account,'account',i));c.appendChild(opts(S.cfg.categories,r.category,'category',i));d.appendChild(opts(S.cfg.changes,r.change,'change',i));tr.appendChild(a);tr.appendChild(c);tr.appendChild(d);t.appendChild(tr)});$('prev').disabled=S.i===0;var last=S.i===S.qs.length-1;$('next').classList.toggle('hide',last);$('send').classList.toggle('hide',!last);navState()}function go(i){if(i<0||i>=S.qs.length)return;S.i=i;save();render();window.scrollTo(0,0)}
function timer(){clearInterval(S.t);tick();S.t=setInterval(tick,1000)}function tick(){var sec=Math.max(0,Math.ceil((new Date(S.a.expiresAt)-Date.now())/1000));$('timer').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');if(sec<=0){clearInterval(S.t);submit()}}function ask(){var n=S.qs.filter(done).length;$('mm').textContent='ตอบแล้ว '+n+' ข้อ ยังไม่ตอบ '+(S.qs.length-n)+' ข้อ';$('modal').classList.remove('hide')}async function submit(){var b=$('send');busy(b,true,'กำลังตรวจ...');try{var r=await gas('submitExam',{attemptId:S.a.attemptId,responses:S.ans});clearInterval(S.t);localStorage.removeItem(K);showResult(r)}catch(e){toast(e.message)}finally{busy(b,false)}}function showResult(r){only('result');$('timer').classList.add('hide');$('status').textContent=r.status;$('pct').textContent=pc(r.percent);$('rn').textContent=r.studentName;$('rm').textContent=r.className+'/'+r.room+' เลขที่ '+r.number+' • ชุด '+r.formId;$('sa').textContent=pc(r.accountPercent);$('sc').textContent=pc(r.categoryPercent);$('sd').textContent=pc(r.changePercent);var m=Math.min(r.accountPercent,r.categoryPercent,r.changePercent);$('rec').textContent=m>=80?'ทำได้ดีในทั้ง 3 ทักษะ':m===r.categoryPercent?'ควรทบทวนการจำแนกบัญชีเป็น สินทรัพย์ หนี้สิน และส่วนของเจ้าของ':m===r.changePercent?'ควรทบทวนการวิเคราะห์ว่าบัญชีเพิ่มขึ้นหรือลดลง':'ควรฝึกระบุบัญชีที่เกี่ยวข้องให้ครบ'}function save(){try{localStorage.setItem(K,JSON.stringify({st:S.st,a:S.a,qs:S.qs,ans:S.ans,i:S.i}))}catch(e){}}function restore(){try{var x=JSON.parse(localStorage.getItem(K)||'null');if(!x||!x.a||Date.now()>new Date(x.a.expiresAt))return false;S.st=x.st;S.a=x.a;S.qs=x.qs;S.ans=x.ans;S.i=x.i||0;showExam();return true}catch(e){return false}}
function bindT(){$('go').onclick=loadT;$('search').oninput=draw;$('csv').onclick=csv}async function loadT(){try{S.db=await gas('getDashboardData',$('key').value.trim());$('login').classList.add('hide');$('db').classList.remove('hide');summary();draw()}catch(e){toast(e.message)}}function summary(){var s=S.db.summary;$('sum').innerHTML=[['ผู้เข้าสอบ',s.total],['ผ่าน',s.pass],['ควรทบทวน',s.review],['เฉลี่ย',pc(s.average)],['สูงสุด',pc(s.highest)],['ต่ำสุด',pc(s.lowest)]].map(function(x){return'<div class="sum">'+x[0]+'<b>'+x[1]+'</b></div>'}).join('')}function esc(x){return String(x==null?'':x).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}function draw(){if(!S.db)return;var q=$('search').value.toLowerCase();$('body').innerHTML=S.db.attempts.filter(function(r){return[r.studentId,r.name,r.room].join(' ').toLowerCase().indexOf(q)>=0}).map(function(r){return'<tr><td>'+esc(r.studentId)+'</td><td>'+esc(r.name)+'</td><td>'+esc(r.className)+'/'+esc(r.room)+'</td><td>'+esc(r.formId)+'</td><td>'+pc(r.percent)+'</td><td>'+pc(r.accountPercent)+'</td><td>'+pc(r.categoryPercent)+'</td><td>'+pc(r.changePercent)+'</td><td>'+esc(r.status)+'</td></tr>'}).join('')}function csv(){if(!S.db)return;var h=['StudentID','Name','Class','Room','Number','Form','Percent','Account','Category','Change','Status'],rows=S.db.attempts.map(function(r){return[r.studentId,r.name,r.className,r.room,r.number,r.formId,r.percent,r.accountPercent,r.categoryPercent,r.changePercent,r.status]});function e(x){x=String(x==null?'':x);return /[\",\\n]/.test(x)?'\"'+x.replace(/\"/g,'\"\"')+'\"':x}var text='\ufeff'+[h].concat(rows).map(function(r){return r.map(e).join(',')}).join('\\n'),b=new Blob([text],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='accounting-test-results.csv';a.click();URL.revokeObjectURL(a.href)}boot()})();
</script></body></html>`;}
